project_id = "xnhxokvtcuwfyxaulaxc"

[functions.unsubscribe]
verify_jwt = false

[functions.import-leads]
verify_jwt = false

[functions.process-scheduled-sends]
verify_jwt = false

[functions.track-visit]
verify_jwt = false

[functions.tracker-script]
verify_jwt = false

[functions.sync-inbox-cron]
verify_jwt = false

[functions.submit-dsr]
verify_jwt = false

[functions.create-credit-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.leads-search]
verify_jwt = false

[functions.leads-reveal]
verify_jwt = false

[functions.leads-import]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.refill-yearly-plan-credits]
verify_jwt = false
